#!/bin/bash
#kurd-patcher
#Karwan BK
#Version 1.0
##############
if [ ! -n "$1" ]; then
echo "Bad Type of Hack Report (Karwanbk@yahoo.com)"
exit 0
fi
if [ -n "$1 $2" ]; then
wget http://repo.kurdios.com/hack/$1/info-hack.plist
fi
if [ ! -f "info-hack.plist" ];then
		echo "Cannot Conect to the Server (repo.kurdios.com)"
    if [ -e "/hack" ];then
    rm -rf /hack
    fi
		exit 0
else
info="/info-hack.plist"
bundl=$(plutil -key Bundle "$info")
workver=$(plutil -key workver "$info")
where=$(plutil -key where "$info")
folder=$(plutil -key folder "$info")
Author=$(plutil -key Author "$info")
message=$(plutil -key message "$info")
note=$(plutil -key Note "$info")
dis=$(plutil -key Discription "$info")
fi 
FindMe $bundl C
if [ -f "/var/mobile/temp.temp" ];then
doc=$(cat "/var/mobile/temp.temp")
app=$(cat "/var/mobile/tempapp.temp")
Nameapp=$(plutil -key CFBundleDisplayName "$app/Info.plist")
binname=$(plutil -key CFBundleExecutable "$app/Info.plist")
	if [ -f "$app/Info.plist" ];then
		if grep -q "bundleShortVersionString" "$app/Info.plist"
		then ver=$(plutil -key bundleShortVersionString "$app/Info.plist")
		fi
		plutil -xml "$app/Info.plist"  2>&1>/dev/null
		if grep -q "CFBundleShortVersionString" "$app/Info.plist"
		then ver=$(plutil -key CFBundleShortVersionString "$app/Info.plist")
		fi
		if grep -q "CFBundleVersion" "$app/Info.plist"
		then ver=$(plutil -key CFBundleVersion "$app/Info.plist")
		fi	
	fi
	if [ "$where" == "D" ]; then
    loc="$doc/Documents$folder"
	fi
	if [ "$where" == "L" ]; then
    loc="$doc/Library$folder"
	fi
	if [ "$where" == "app" ]; then
    loc="$app$folder"
	fi	
else
echo -n " -Finding $bundl ..."
sleep 1
echo " not found. if your sure its install please report to the repo manager"
    if [ -e "$info" ];then
    rm -rf $info
    fi
    if [ -e "/hack" ];then
    rm -rf /hack
    fi
exit 0
fi
if [ "$2" == "i" ]; then
#Hacking
    sign="0"
	echo
	sleep 1
	echo -n " -Finding $Nameapp ..."
	sleep 1
	if [ -f "/var/mobile/temp.temp" ];then
	echo " Success"
	else
	echo " Not Found please install $Nameapp First"
	if [ -f "$info" ];then
	rm -rf $info
	rm -rf /hack
	fi
	exit 0
	fi
	echo ""
	echo "###########"
	echo "# Discription #"
	echo "###########"
	echo ""
	echo "$dis"
	sleep 1
	echo ""

	gamefiles=/files.tmp
	hackedfiles=/hackedfiles.tmp
	matchingfiles=/matchingfiles.tmp
	echo -n " -Checking Hacked Files ..."
	if [ ! -d "/hack" ]; then
		sleep 2
		echo
		echo " *** Error ***"
		echo
		echo "*********************************"
		echo "	 *No hacked files found in /hack***"
		echo "	 *Please report this to the repo manager"
		echo
		echo "*********************************"
		echo
	rm -rf $info
	rm "/var/mobile/temp.temp"
	rm "/var/mobile/tempapp.temp"
		exit 0
	else
		sleep 1
		echo " Success"
	fi
	echo -n " -Killing $Nameapp ..."
	sleep 1
	killall "$binname" &>/dev/null
	echo " Success"
	sleep 1
	echo -n " -Making Backup ..."
	ls $loc/ >$gamefiles
	ls "/hack" >$hackedfiles
	grep -i -E -f $gamefiles $hackedfiles >$matchingfiles

	for line in `cat $matchingfiles`
	do zip -9 -ru "$loc/../backup.zip" "$loc/$line"&>/dev/null
	done
	if [ -e "$loc/../backup.zip" ]; then
		sleep 1
		echo " Success"
	else
		sleep 1
		echo " *** Error ***"
		echo
		echo "******************************"
		echo "	*Backup not needed, not replacing anything"
		echo
		echo "******************************"
	fi
	echo -n " -Checking App Version ..."
	if [ ! "$workver" == "$ver" ]; then
		sleep 1
		 echo "*** Note! ***" 
 echo 
 echo "********************************" 
 echo "*** Your app is version $ver ***" 
 echo "*** This hack is made on version $workver ***" 
 echo "*** The hack Maybe didn't work on your Version ***" 
 echo "********************************" 
 
		sleep 2
	else 
		sleep 1
		echo " Success"
	fi
	echo -n " -Patching Files ..."
	sleep 1
	cp -rf "/hack"/* "$loc"
	echo " Success"
	sleep 1
	echo -n " -Setting Ownership and Permissions ..."
	sleep 1
	chmod -R 755 "$loc"
	chown -R mobile.mobile "$loc"
	echo " Success"
	if [ $sign = "1" ];then
	ldone "$loc/$binname" -s
	fi
    echo -n " -Cleaning Up ..."
	sleep 1
	rm -f $gamefiles $hackedfiles $matchingfiles
	rm -rf $info
	rm -rf /hack
	rm "/var/mobile/temp.temp"
	rm "/var/mobile/tempapp.temp"
	echo " Success"
	sleep 1
	echo ""
	echo " -$Nameapp Successfully Hacked :)"
	sleep 1
	echo ""
	echo "$message"
	$note
	echo
	echo "***********************************"
	echo "***********************************"
	sleep 1
	echo
	echo "- Hack By $Author"
	echo " - Using Kurd-patcher by (Karwan BK)"
	sleep 1
	echo "- Exclusive on Repo.Kurdios.Com"
	sleep 1
	echo "- Enjoy !"
	echo ""
	sleep 2
fi 
if [ "$2" == "r" ]; then
#removeHack
	if [ -e "/hack" ];then
	rm -rf /hack
	fi
	echo ""
	echo -n " -Finding $Nameapp ..."
	sleep 1
	if [ -f "/var/mobile/temp.temp" ];then
	echo " Success"
	else
	echo " $Nameapp Not Found, asuming that its been uninstalled"
	if [ -f "$info" ];then
	rm -rf $info
	fi
	if [ -f "/var/mobile/temp.temp" ];then
	rm "/var/mobile/temp.temp"
	fi
	if [ -f "/var/mobile/tempapp.temp" ];then
	rm "/var/mobile/tempapp.temp"
	fi
	exit 0
	fi
	echo -n " -Killing $Nameapp ... "
	sleep 1
	killall "$binname" &>/dev/null
	echo " Success"
	sleep 1 
	echo -n " -Restoring files..."
	if [ -f "$loc/../backup.zip" ]; then
		sleep 1
	unzip -XKo "$loc/../backup.zip" &>/dev/null
	rm "$loc/../backup.zip" 		
		echo " Success"
		echo " -Hacked files have now been replaced by the Original files"     
	else
		sleep 1
		echo " *** Error ***"
		echo
		echo "********************************"
		echo "	*Backup not found maybe there was no backup"
		echo
		echo "********************************"
	fi

	$note
	echo "$message"
	echo
	sleep 1
	echo "**********************"
	echo " - Hack by $Author"
	echo " - Thank you for using Repo.Kurdios.com"
	echo " - Only for Repo.Kurdios.com"
fi
if [ -f "$info" ];then
rm -rf $info
fi
if [ -f "/var/mobile/temp.temp" ];then
rm "/var/mobile/temp.temp"
fi
if [ -f "/var/mobile/tempapp.temp" ];then
rm "/var/mobile/tempapp.temp"
fi
if [ -e "/hack" ];then
rm -rf /hack
fi
if [[ "$2" != "r" && "$2" != "i" ]]; then
echo "Nothing To do"
exit 0
fi



